#! /bin/sh

### BEGIN INIT INFO
# Provides:          e6nomni
# Required-Start:    $remote_fs $all
# Required-Stop:     $remote_fs $all
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: polestart start script
# Description:       polestart start script
### END INIT INFO

do_start(){
    /etc/rc.nomni2
}

case "$1" in
  start)
        do_start
        ;;
  restart|reload|force-reload)
        exit 3
        ;;
  stop|status)
        exit 3
        ;;
  *)
        exit 3
        ;;
esac
