#!/bin/sh

touch /rst_cka

LIMIT_CNT=0

case "$1" in
'start')
    touch /rst_ckb
    /etc/rc.nomni2
    sleep 3 
        ;;
'stop')
        ;;
*)
        echo "Usage: $0 { start | stop }"
        exit 1
        ;;
esac
exit 0
